### ISSUE TITLE
Modification actions on :end-of-message fails

### ISSUE THREAD

**Issue by amakurin** [fourtytoo/demyjtify#1]
Hi! I have the problem with send modify actions on the eom. 
Milter is just hangs out after first of action and postfix wait until timeout expired. If i just send accept action - all works, but not change-header nor add-header works.
I've tried to add actions in context before options with no luck. I saw your example gnutp, but it does not look to be working, at least you do not pass handlers to start-milter.
Code 
(define-event-handlers handlers
...
  (send-action {:action :add-header
                   :name "X-Clacks-Overhead"
                   :value "GNU Terry Pratchett"}
                  context)
   (default-event-handler event context))) 
works exactly as described before. I'm using postfix 2.11.
And see milter log entry after which it hangs
<< {:action :add-header, :name X-Clacks-Overhead, :value GNU Terry Pratchett}

Have you any thoughts about this? Thanks in advance!

**Comment by fourteatoo** [comment]
Apologies to Sir Terry Pratchett.  That example was never tested.
Try and get the latest version that fixes also a bug in the action processing.

**Comment by amakurin** [comment]
Yep! That is the fix! Thanks a lot!
